### ISSUE TITLE
README.md page for the knowledge share

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/turing-roche-partnership#19]
To allow browsing of all knowledge share events, I suggest creating a README.md that displays a table here: https://github.com/alan-turing-institute/turing-roche-partnership/tree/main/communications/knowledge-share-series

The table can be structured as following:

| Date | Theme | Speaker(s) | Slidedeck | Video |
|:-----|:--------|:-----------|:----------|:-------|
| June 2023 | Personalised Medicine in the face of multi scale heterogeneity | [Dr. Chris Banerji](https://www.turing.ac.uk/people/research-associates/chris-banerji) | [Slidedeck](https://github.com/alan-turing-institute/turing-roche-partnership/blob/main/communications/knowledge-share-series/june-2023/Chris%20Banerji%20Slides%20Turing%20Roche%20Knowledge%20Share.pdf) | [Video on YouTube](https://www.youtube.com/watch?v=qo4_H5-Tpyo) |

Can you convince speakers to publish their slides on Zenodo? 
Is there a Turing-Roche Zenodo community page?

**Comment by vhellon** [comment]
Great shout thanks- have done now! Was looking into a Zenodo for the partnership so will consider this a venue for the slides too
