### ISSUE TITLE
newsletter july 2022

### ISSUE THREAD

**Issue by vhellon** [alan-turing-institute/turing-roche-partnership#5]
will be going out around 8th july- please comment with any content you'd like included

**Comment by vhellon** [comment]
Volunteers wanted for RSS editorial board
 
The Royal Statistical Society (RSS) is looking for volunteers to join an editorial board to help shape the development of a new data science content platform. The new platform will host technical resources and case studies to support the data science community.
 
Editorial board members will help develop editorial strategy, source ideas, and write, commission, and review content, among other duties.
 
To apply, please send a CV and a covering letter (containing a brief biographic sketch and a statement about why you are interested in the role) to [b.tarran@rss.org.uk](mailto:b.tarran@rss.org.uk). Please also email with any questions about the role.

**Comment by vhellon** [comment]
https://www.eventbrite.co.uk/e/genomic-equity-series-getting-genetic-ancestry-right-for-society-society-tickets-377461677037

**Comment by vhellon** [comment]
https://www.turing.ac.uk/events/understanding-impact-pandemic

**Comment by vhellon** [comment]
https://www.turing.ac.uk/events/rsf-seminar-series-new-findings-age-dependent-topic-modelling-multiple-long-term-conditions

**Comment by vhellon** [comment]
http://www.compstat2022.org/

**Comment by mrllynn** [comment]
Thank you for including me. :-)

**Comment by vhellon** [comment]
@mrllynn Hi Muriel- just checking if you've got anything you'd like to include in the newsletter or were you referring to what's already being included? :)

**Comment by mrllynn** [comment]
Excuse me for the inconvenience, this is a misunderstanding.
All good from my side.
